# 开发环境配置
server:
  port: 8081
  context-path: /sell


spring:
  #数据库的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell_weixin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: sixkery

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    default-property-inclusion: non_null
  # redis 的配置
  redis:
    host: 192.168.42.133
    port: 6379

## 日志的配置
#logging:
#    # 日志文件存放位置
#  file:
#    name: log/blog-dev.log
## 日志的配置

# 微信配置
wechat:
  mpAppId: qwdsdfsa
  mpAppSecret: asdasff1334
  openAppId: q2efd
  openAppSecret: dfsg
  mckId: 12dfsfdv
  mchKey: gsh
  keyPath: asdfaftera
  notifyUrl: awsefterfg

projectUrl:
  wechatMpAuthorize: http://127.0.0.1:8081
  wechatOpenAuthorize: http://127.0.0.1:8081
  sell: http://127.0.0.1:8081
